version: "3.4"
services:
  TaskHub:
    image: taskhub
    ports:
      - "5000:8080"
  TaskHub-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1533:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Senha@123
volumes:
  mssql-data:
    driver: local